language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk12

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - ./webapp/jass-tournament-ui/build/npm/
    - ./webapp/jass-tournament-ui/build/nodejs/
    - ./webapp/jass-tournament-ui/node_modules/

script:
  - ./gradlew test
  - ./gradlew webapp:jass-tournament-ui:npm_run_lint
  - ./gradlew webapp:jass-tournament-ui:npm_run_ci-test
  - ./gradlew webapp:jass-tournament-ui:npm_run_ci-e2e